sudo: required
services:
  - docker

before_install:
  - docker build -t mhussain78/docker-react -f Dockerfile.dev .

script:
  - docker run mhussain78/docker-react npm run test -- --coverage --watchAll=false