sudo: required
services:
  - docker

before_install:
  - docker build -t mhussain78/docker-react -f Dockerfile.dev .

script:
  - docker run mhussain78/docker-react npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-700317628932"
  bucket_path: "docker-react"
  on:
   branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY